[package]
name = "xinput_link_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xinput_link_lib = { path = "lib" }
